
// Album actions
export const LP_COLLECTION_REQUEST = 'LP_COLLECTION_REQUEST'
export const LP_COLLECTION_SUCCESS = 'LP_COLLECTION_SUCCESS'
export const LP_COLLECTION_FAIL = 'LP_COLLECTION_FAIL'

export const LP_ADD_REQUEST = 'LP_ADD_REQUEST'
export const LP_ADD_SUCCESS = 'LP_ADD_SUCCESS'
export const LP_ADD_FAIL = 'LP_ADD_FAIL'

export const LP_AUTOCOMPLETE_SEARCH_REQUEST = 'LP_AUTOCOMPLETE_SEARCH_REQUEST'
export const LP_AUTOCOMPLETE_SEARCH_SUCCESS = 'LP_AUTOCOMPLETE_SEARCH_SUCCESS'
export const LP_AUTOCOMPLETE_SEARCH_FAIL = 'LP_AUTOCOMPLETE_SEARCH_FAIL'
export const LP_AUTOCOMPLETE_SEARCH_CLEAR = 'LP_AUTOCOMPLETE_SEARCH_CLEAR'

export const LP_FETCH_EXTERNAL_DATA_REQUEST = 'LP_FETCH_EXTERNAL_DATA_REQUEST'
export const LP_FETCH_EXTERNAL_DATA_SUCCESS = 'LP_FETCH_EXTERNAL_DATA_SUCCESS'
export const LP_FETCH_EXTERNAL_DATA_FAIL = 'LP_FETCH_EXTERNAL_DATA_FAIL'