
// Album actions
export const LP_COLLECTION_REQUEST = 'LP_COLLECTION_REQUEST'
export const LP_COLLECTION_SUCCESS = 'LP_COLLECTION_SUCCESS'
export const LP_COLLECTION_FAIL = 'LP_COLLECTION_FAIL'

export const LP_FETCH_EXTERNAL_DATA_REQUEST = 'LP_FETCH_EXTERNAL_DATA_REQUEST'
export const LP_FETCH_EXTERNAL_DATA_SUCCESS = 'LP_FETCH_EXTERNAL_DATA_SUCCESS'
export const LP_FETCH_EXTERNAL_DATA_FAIL = 'LP_FETCH_EXTERNAL_DATA_FAIL'