
// Album actions
export const LP_COLLECTION_REQUEST = 'LP_COLLECTION_REQUEST'
export const LP_COLLECTION_SUCCESS = 'LP_COLLECTION_SUCCESS'
export const LP_COLLECTION_FAIL = 'LP_COLLECTION_FAIL'

export const LP_ADD_REQUEST = 'LP_ADD_REQUEST'
export const LP_ADD_SUCCESS = 'LP_ADD_SUCCESS'
export const LP_ADD_FAIL = 'LP_ADD_FAIL'

export const LP_ADD_COVER_REQUEST = 'LP_ADD_COVER_REQUEST'
export const LP_ADD_COVER_SUCCESS = 'LP_ADD_COVER_SUCCESS'
export const LP_ADD_COVER_FAIL = 'LP_ADD_COVER_FAIL'

export const LP_AUTOCOMPLETE_SEARCH_REQUEST = 'LP_AUTOCOMPLETE_SEARCH_REQUEST'
export const LP_AUTOCOMPLETE_SEARCH_SUCCESS = 'LP_AUTOCOMPLETE_SEARCH_SUCCESS'
export const LP_AUTOCOMPLETE_SEARCH_FAIL = 'LP_AUTOCOMPLETE_SEARCH_FAIL'
export const LP_AUTOCOMPLETE_SEARCH_CLEAR = 'LP_AUTOCOMPLETE_SEARCH_CLEAR'

export const LP_FETCH_EXTERNAL_DATA_REQUEST = 'LP_FETCH_EXTERNAL_DATA_REQUEST'
export const LP_FETCH_EXTERNAL_DATA_SUCCESS = 'LP_FETCH_EXTERNAL_DATA_SUCCESS'
export const LP_FETCH_EXTERNAL_DATA_FAIL = 'LP_FETCH_EXTERNAL_DATA_FAIL'
export const LP_FETCH_EXTERNAL_DATA_CLEAR = 'LP_FETCH_EXTERNAL_DATA_CLEAR'

export const LP_DELETE_REQUEST = 'LP_DELETE_REQUEST'
export const LP_DELETE_SUCCESS = 'LP_DELETE_SUCCESS'
export const LP_DELETE_FAIL = 'LP_DELETE_FAIL'

export const LP_DETAILS_REQUEST = 'LP_DETAILS_REQUEST'
export const LP_DETAILS_SUCCESS = 'LP_DETAILS_SUCCESS'
export const LP_DETAILS_FAIL = 'LP_DETAILS_FAIL'
export const LP_DETAILS_CLEAR = 'LP_DETAILS_CLEAR'

export const LP_UPDATE_REQUEST = 'LP_DETAILS_REQUEST'
export const LP_UPDATE_SUCCESS = 'LP_DETAILS_SUCCESS'
export const LP_UPDATE_FAIL = 'LP_DETAILS_FAIL'
export const LP_UPDATE_CLEAR = 'LP_DETAILS_CLEAR'

export const LP_EDIT_COVER_REQUEST = 'LP_EDIT_COVER_REQUEST'
export const LP_EDIT_COVER_SUCCESS = 'LP_EDIT_COVER_SUCCESS'
export const LP_EDIT_COVER_FAIL = 'LP_EDIT_COVER_FAIL'

export const LP_EDIT_REQUEST = 'LP_EDIT_REQUEST'
export const LP_EDIT_SUCCESS = 'LP_EDIT_SUCCESS'
export const LP_EDIT_FAIL = 'LP_EDIT_FAIL'
