export const LIST_LP_FORSALE_REQUEST = 'LIST_LP_FORSALE_REQUEST'
export const LIST_LP_FORSALE_SUCCESS = 'LIST_LP_FORSALE_SUCCESS'
export const LIST_LP_FORSALE_FAIL = 'LIST_LP_FORSALE_FAIL'

export const UNLIST_LP_FORSALE_REQUEST = 'UNLIST_LP_FORSALE_REQUEST'
export const UNLIST_LP_FORSALE_SUCCESS = 'UNLIST_LP_FORSALE_SUCCESS'
export const UNLIST_LP_FORSALE_FAIL = 'UNLIST_LP_FORSALE_FAIL'

export const LISTED_ITEMS_REQUEST = 'LISTED_ITEMS_REQUEST'
export const LISTED_ITEMS_SUCCESS = 'LISTED_ITEMS_SUCCESS'
export const LISTED_ITEMS_FAIL = 'LISTED_ITEMS_FAIL'
export const LISTED_ITEMS_CLEAR = 'LISTED_ITEMS_CLEAR'

export const MAKE_OFFER_REQUEST = 'MAKE_OFFER_REQUEST'
export const MAKE_OFFER_SUCCESS = 'MAKE_OFFER_SUCCESS'
export const MAKE_OFFER_FAIL = 'MAKE_OFFER_FAIL'

export const LOAD_RECEIVED_OFFERS_REQUEST = 'LOAD_RECEIVED_OFFERS_REQUEST'
export const LOAD_RECEIVED_OFFERS_SUCCESS = 'LOAD_RECEIVED_OFFERS_SUCCESS'
export const LOAD_RECEIVED_OFFERS_FAIL = 'LOAD_RECEIVED_OFFERS_FAIL'
export const LOAD_RECEIVED_OFFERS_CLEAR = 'LOAD_RECEIVED_OFFERS_CLEAR'

export const LOAD_SENDED_OFFERS_REQUEST = 'LOAD_SENDED_OFFERS_REQUEST'
export const LOAD_SENDED_OFFERS_SUCCESS = 'LOAD_SENDED_OFFERS_SUCCESS'
export const LOAD_SENDED_OFFERS_FAIL = 'LOAD_SENDED_OFFERS_FAIL'
export const LOAD_SENDED_OFFERS_CLEAR = 'LOAD_SENDED_OFFERS_CLEAR'

export const REJECT_OFFER_REQUEST = 'REJECT_OFFER_REQUEST'
export const REJECT_OFFER_SUCCESS = 'REJECT_OFFER_SUCCESS'
export const REJECT_OFFER_FAIL = 'REJECT_OFFER_FAIL'

export const ACCEPT_OFFER_REQUEST = 'ACCEPT_OFFER_REQUEST'
export const ACCEPT_OFFER_SUCCESS = 'ACCEPT_OFFER_SUCCESS'
export const ACCEPT_OFFER_FAIL = 'ACCEPT_OFFER_FAIL'

export const RATE_OFFER_REQUEST = 'RATE_OFFER_REQUEST'
export const RATE_OFFER_SUCCESS = 'RATE_OFFER_SUCCESS'
export const RATE_OFFER_FAIL = 'RATE_OFFER_FAIL'
