export const LIST_LP_FORSALE_REQUEST = 'LIST_LP_FORSALE_REQUEST'
export const LIST_LP_FORSALE_SUCCESS = 'LIST_LP_FORSALE_SUCCESS'
export const LIST_LP_FORSALE_FAIL = 'LIST_LP_FORSALE_FAIL'

export const UNLIST_LP_FORSALE_REQUEST = 'UNLIST_LP_FORSALE_REQUEST'
export const UNLIST_LP_FORSALE_SUCCESS = 'UNLIST_LP_FORSALE_SUCCESS'
export const UNLIST_LP_FORSALE_FAIL = 'UNLIST_LP_FORSALE_FAIL'