export const USER_LIST_REQUEST = 'USER_LIST_REQUEST'
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS'
export const USER_LIST_FAIL = 'USER_LIST_FAIL'
export const USER_LIST_CLEAR = 'USER_LIST_CLEAR'

export const USER_DETAIL_REQUEST = 'USER_DETAIL_REQUEST'
export const USER_DETAIL_SUCCESS = 'USER_DETAIL_SUCCESS'
export const USER_DETAIL_FAIL = 'USER_DETAIL_FAIL'
export const USER_DETAIL_CLEAR = 'USER_DETAIL_CLEAR'

export const USER_FOLLOW_REQUEST = 'USER_FOLLOW_REQUEST'
export const USER_FOLLOW_SUCCESS = 'USER_FOLLOW_SUCCESS'
export const USER_FOLLOW_FAIL = 'USER_FOLLOW_FAIL'

export const USER_UNFOLLOW_REQUEST = 'USER_UNFOLLOW_REQUEST'
export const USER_UNFOLLOW_SUCCESS = 'USER_UNFOLLOW_SUCCESS'
export const USER_UNFOLLOW_FAIL = 'USER_UNFOLLOW_FAIL'