export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'
export const USER_LOGGGED_OUT = 'USER_LOGGGED_OUT'

export const GOOGLE_LOGIN_REQUEST = 'GOOGLE_LOGIN_REQUEST'
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS'
export const GOOGLE_LOGIN_FAIL = 'GOOGLE_LOGIN_FAIL'

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST'
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS'
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL'

export const USER_UPLOAD_PICTURE_REQUEST = 'USER_UPLOAD_PICTURE_REQUEST'
export const USER_UPLOAD_PICTURE_SUCCESS = 'USER_UPLOAD_PICTURE_SUCCESS'
export const USER_UPLOAD_PICTURE_FAIL = 'USER_UPLOAD_PICTURE_FAIL'

export const USER_EDIT_PROFILE_REQUEST = 'USER_EDIT_PROFILE_REQUEST'
export const USER_EDIT_PROFILE_SUCCESS = 'USER_EDIT_PROFILE_SUCCESS'
export const USER_EDIT_PROFILE_FAIL = 'USER_EDIT_PROFILE_FAIL'

export const USER_SESSION_EXPIRED = 'USER_SESSION_EXPIRED'